spring:
  application:
    name: lishe-app
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/lisheapp
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
twilio:
  account:
    sid: AC4e625617af69a257c9062c97196370fd
  auth:
    token: 8c900175c4b99f3dfebaae4accaf085d
  phone:
    number: +18447556236
server:
  error:
    include-message: always
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
