spring:
  application:
    name: lishe-app
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/lisheapp
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
clickSend-username: y4clab@gmail.com
clickSend-apiKey: EBB1979A-4A71-CA68-E5DE-0ECA57086FB6
server:
  error:
    include-message: always
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
clickSend-username: y4clab@gmail.com
clickSend-apiKey: EBB1979A-4A71-CA68-E5DE-0ECA57086FB6
server:
  error:
    include-message: always
logging:
  level:
    root: info