// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDefa1DKoAIODqwFgjXNlAGE03ueCelN0c',
    appId: '1:44733792899:web:c8a70f36a546b9c41591b6',
    messagingSenderId: '44733792899',
    projectId: 'lishe-app-639b0',
    authDomain: 'lishe-app-639b0.firebaseapp.com',
    storageBucket: 'lishe-app-639b0.firebasestorage.app',
    measurementId: 'G-FKX6N6KV75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRTpZ1vOrnkzpTSUbiDE6pr405fnNi5N8',
    appId: '1:44733792899:android:0f9403fb5206ed4d1591b6',
    messagingSenderId: '44733792899',
    projectId: 'lishe-app-639b0',
    storageBucket: 'lishe-app-639b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUxUYm0B5GnyfMQwQGy-tJOxTecfppsE',
    appId: '1:44733792899:ios:45360a4bba6e86ba1591b6',
    messagingSenderId: '44733792899',
    projectId: 'lishe-app-639b0',
    storageBucket: 'lishe-app-639b0.firebasestorage.app',
    iosBundleId: 'com.example.lisheApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKUxUYm0B5GnyfMQwQGy-tJOxTecfppsE',
    appId: '1:44733792899:ios:45360a4bba6e86ba1591b6',
    messagingSenderId: '44733792899',
    projectId: 'lishe-app-639b0',
    storageBucket: 'lishe-app-639b0.firebasestorage.app',
    iosBundleId: 'com.example.lisheApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDefa1DKoAIODqwFgjXNlAGE03ueCelN0c',
    appId: '1:44733792899:web:67e2a980c60e722a1591b6',
    messagingSenderId: '44733792899',
    projectId: 'lishe-app-639b0',
    authDomain: 'lishe-app-639b0.firebaseapp.com',
    storageBucket: 'lishe-app-639b0.firebasestorage.app',
    measurementId: 'G-5P86RKLPY3',
  );
}
